name: ders_calisma_programi
description: Soru çözme gelişimimizi takip edebildiğimiz ders çalışma programı

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  google_mobile_ads: ^2.3.0
  path_provider: ^2.0.11
  sqflite: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
